### ISSUE TITLE
能否添加分辨率信息

### ISSUE THREAD

**Issue by lee911214** [leaicc/Hlt#1]
如题，大佬能否添加下，如视频分辨率是1920*1080，可在顶部文件名旁边添加

**Comment by leaicc** [comment]
抱歉啊，没有找到分辨率参数的相关命令，我也不会修改

**Comment by leaicc** [comment]
抱歉啊，没有找到分辨率的相关命令，你可以找一个带有分辨率的皮肤发给我，我看看能不能查到分辨率的命令参数

**Comment by lee911214** [comment]
> 抱歉啊，没有找到分辨率的相关命令，你可以找一个带有分辨率的皮肤发给我，我看看能不能查到分辨率的命令参数

https://pan.baidu.com/share/init?surl=_wCwuRpt6EIV7VzdMkdWWQ#list/path=%2F&parentPath=%2F

密码mleg

你看下这个哈  Kardox 汉化 

麻烦啦

**Comment by leaicc** [comment]
> > 抱歉啊，没有找到分辨率的相关命令，你可以找一个带有分辨率的皮肤发给我，我看看能不能查到分辨率的命令参数
> 
> https://pan.baidu.com/share/init?surl=_wCwuRpt6EIV7VzdMkdWWQ#list/path=%2F&parentPath=%2F
> 
> 密码mleg
> 
> 你看下这个哈 Kardox 汉化
> 
> 麻烦啦

由于无法获取视频标题长度，所以把分辨率加到了截图按钮后面，类似你给我发的那个皮肤
链接: https://pan.baidu.com/s/1QcrvHOKe8FKGOHr9IQ-u1A 提取码: ys2d

**Comment by lee911214** [comment]
> > > 抱歉啊，没有找到分辨率的相关命令，你可以找一个带有分辨率的皮肤发给我，我看看能不能查到分辨率的命令参数
> > 
> > 
> > https://pan.baidu.com/share/init?surl=_wCwuRpt6EIV7VzdMkdWWQ#list/path=%2F&parentPath=%2F
> > 密码mleg
> > 你看下这个哈 Kardox 汉化
> > 麻烦啦
> 
> 由于无法获取视频标题长度，所以把分辨率加到了截图按钮后面，类似你给我发的那个皮肤 链接: https://pan.baidu.com/s/1QcrvHOKe8FKGOHr9IQ-u1A 提取码: ys2d

可以可以 ，非常感谢
